package engine

import (
	"fmt"
	"math"

	"github.com/cwbudde/algo-dsp/dsp/core"
	"github.com/cwbudde/algo-dsp/dsp/signal"
)

// toneSource is the Phase 0 test signal: a sine read from a one-second
// wavetable generated by algo-dsp.
//
// algo-dsp's generator is one-shot (it always starts at phase zero), so the
// stream is made continuous by looping a table that holds a whole number of
// cycles. A one-second table at an integer sample rate does exactly that as
// long as the frequency is an integer, which is why the frequency is rounded.
type toneSource struct {
	table     []float32
	pos       int
	frequency float64
	amplitude float64
}

func newToneSource(sampleRate, frequencyHz, amplitude float64) (*toneSource, error) {
	t := &toneSource{}
	if err := t.configure(sampleRate, frequencyHz, amplitude); err != nil {
		return nil, err
	}

	return t, nil
}

func (t *toneSource) configure(sampleRate, frequencyHz, amplitude float64) error {
	freq := math.Round(frequencyHz)
	if freq < 1 || freq >= sampleRate/2 {
		return fmt.Errorf("tone frequency %.1f Hz outside (0, %.0f)", frequencyHz, sampleRate/2)
	}

	if amplitude < 0 || amplitude > 1 || math.IsNaN(amplitude) {
		return fmt.Errorf("tone amplitude %v outside [0, 1]", amplitude)
	}

	gen := signal.NewGenerator(core.WithSampleRate(sampleRate))

	samples, err := gen.Sine(freq, amplitude, int(sampleRate))
	if err != nil {
		return fmt.Errorf("generate tone table: %w", err)
	}

	table := make([]float32, len(samples))
	for i, s := range samples {
		table[i] = float32(s)
	}

	// Keep the read position proportionally the same so a retune does not
	// restart the cycle audibly; the modulo guards a shorter table.
	if len(t.table) > 0 {
		t.pos = t.pos * len(table) / len(t.table)
	}

	t.pos %= len(table)
	t.table = table
	t.frequency = freq
	t.amplitude = amplitude

	return nil
}

// render writes len(dst)/channels interleaved frames, the same sample on
// every channel.
func (t *toneSource) render(dst []float32, channels int) {
	frames := len(dst) / channels
	for f := range frames {
		s := t.table[t.pos]

		t.pos++
		if t.pos == len(t.table) {
			t.pos = 0
		}

		for c := range channels {
			dst[f*channels+c] = s
		}
	}
}
